### ISSUE TITLE
Some problem about mcs_hard.pkl test dataset

### ISSUE THREAD

**Issue by hzxwonder** [squareRoot3/GraphArena#1]
I output a mcs_hard.pkl test dataset for inspection, and find that the "path" of all the data is none, so if the output of check_solution functions is -1, is this evaluation reasonable? Is it possible to test the capabilities of LLMs on this dataset?

**Comment by squareRoot3** [comment]
Thank you for your interest!

The 'path' in the dataset generated by the exact solver is not used in the benchmarking. It is provided only for reference.

The evaluation process consists of the following steps:
1. Extract the path from the LLM's response.
2. Check and score the path.
3. Compare the score with each other or the approximated/exact traditional solvers.

Let's use the check_solution function in MCS as an example:
- A score of -1 indicates that we failed to extract two subgraphs from the output.
- A score of -2 means we detected two subgraphs, but they are not isomorphic.
- A positive score represents the size of the common subgraph successfully found by the LLM.

```
    def check_solution(self, problem_id, response):
        pattern = r"\[\s*([\d\s,]+)\s*\]"
        # Search for the pattern in the response
        matches = re.findall(pattern, response)
        if len(matches) >= 2:
            try:
                molecule_a_indices = tuple(map(int, re.split(r'[\s,]+', matches[-2].strip())))
                molecule_b_indices = tuple(map(int, re.split(r'[\s,]+', matches[-1].strip())))
                if molecule_a_indices and molecule_b_indices and len(molecule_a_indices) == len(molecule_b_indices):
                    g1, g2 = self.problem_set[problem_id]['graph']
                    subgraph1 = g1.subgraph(molecule_a_indices)
                    subgraph2 = g2.subgraph(molecule_b_indices)
                    # print(subgraph1, subgraph2)
                    if nx.is_isomorphic(subgraph1, subgraph2):
                        return len(molecule_a_indices)
                return -2
            except Exception as e:
                print(e)
                return -1
        return -1
```

The 'path' of the dataset is updated. For some problems in MCS and GED (hard), the 'path' is still None because the exact solver is too slow to compute a solution.

**Comment by hzxwonder** [comment]
Thank you for your reply! I have one more question. If a difficult MCS and GED problem results in 'None' for the path obtained using the solver, and 'None' for the path obtained using the LLM, according to the code logic, the LLM's score would be -1. Is this reasonable?

**Comment by squareRoot3** [comment]
If the LLM's score is -1, it means we fail to extract two subgraphs from the LLMs' output, no matter the path of the dataset is None or others. MCS and GED tasks have two solvers. If the exact solver returns None, approximated solver is used.
